name: Secret Scan with Gitleaks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2.1.0
        with:
          config: .gitleaks.toml  # Optional: Path to a custom Gitleaks config file in your repo
          verbose: true           # Optional: Set to true to see detailed scan output
