name: Secret Scan with Gitleaks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2.1.0
